# Generated by Django 6.0.4 on 2026-04-18 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='conv_type',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_type',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AIAssist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(max_length=50)),
                ('sentiment', models.CharField(blank=True, max_length=30)),
                ('suggestion', models.TextField()),
                ('context_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assists', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
